// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hziqynsfvfdlfwliroik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6aXF5bnNmdmZkbGZ3bGlyb2lrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwMTQ2MDEsImV4cCI6MjA5MTU5MDYwMX0.95aIopt0sQHXa34JbVL-sNnU4NOgsvR3ULpPgnZT0Os";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});